converting
asSpecifiedChannel: aDSUnspecifiedChannel 
	<return: #DSGuildTextChannel>
	^ DSGuildTextChannel new
		id: aDSUnspecifiedChannel id;
		guildId: aDSUnspecifiedChannel guildId;
		position: aDSUnspecifiedChannel position;
		permissionOverwrites: aDSUnspecifiedChannel permissionOverwrites;
		name: aDSUnspecifiedChannel name;
		topic: aDSUnspecifiedChannel topic;
		nsfw: aDSUnspecifiedChannel nsfw;
		lastMessageId: aDSUnspecifiedChannel lastMessageId;
		icon: aDSUnspecifiedChannel icon;
		parentId: aDSUnspecifiedChannel parentId;
		yourself