accessing
encodedFuelIdString
	"Return FuelId composed of:
		- guild id where a user message was sent
		- channel id where a user message was sent
		- message id, a random number that identifies a message in a FUEL field
		- DateAndTime object as a string
		- channel id where messages with serialized data where sent (it may be the same as channel id)
		- 3 message ids that includes the serialized data as attachments"
	^ '273GA1R5Z40A-273GA1R5Z40A-AN5QPEHHE27K-OS9E1M-2I5EYJH92H35-2I5H15RM0FEO-2I5H1BFMAP6Y-2I5H1EBY2134'