converting
asSpecifiedChannel: aDSUnspecifiedChannel 
	<return: #DSGuildVoiceChannel>
	^ DSGuildVoiceChannel new
		id: aDSUnspecifiedChannel id;
		guildId: aDSUnspecifiedChannel guildId;
		position: aDSUnspecifiedChannel position;
		permissionOverwrites: aDSUnspecifiedChannel permissionOverwrites;
		name: aDSUnspecifiedChannel name;
		bitrate: aDSUnspecifiedChannel bitrate;
		userLimit: aDSUnspecifiedChannel userLimit;
		parentId: aDSUnspecifiedChannel parentId;
		yourself