SystemOrganization addCategory: #'Discord-Gateway'!
SystemOrganization addCategory: 'Discord-Gateway-API'!
SystemOrganization addCategory: 'Discord-Gateway-Announcements'!
SystemOrganization addCategory: 'Discord-Gateway-Commands'!
SystemOrganization addCategory: 'Discord-Gateway-Manifest'!
SystemOrganization addCategory: 'Discord-Gateway-Model'!
SystemOrganization addCategory: 'Discord-Gateway-Traits'!
SystemOrganization addCategory: 'Discord-Gateway-Utility'!
