mapping - payload
payloadMappingFor: aNeoJSONMapper 
	self 
		helloPayloadMappingFor: aNeoJSONMapper;
		identityPayloadMappingFor: aNeoJSONMapper;
		dispatchReadyEventPayloadMappingFor: aNeoJSONMapper;
		resumePayloadMappingFor: aNeoJSONMapper;
		heartbeatPayloadMappingFor: aNeoJSONMapper;
		invalidSessionPayloadMappingFor: aNeoJSONMapper;
		heartbeatAckPayloadMappingFor: aNeoJSONMapper;
		messageCreatePayloadMappingFor: aNeoJSONMapper;
		presenceUpdatePayloadMappingFor: aNeoJSONMapper;
		messageUpdatePayloadMappingFor: aNeoJSONMapper;
		guildCreatePayloadMappingFor: aNeoJSONMapper;
		guildDeletePayloadMappingFor: aNeoJSONMapper;
		guildUpdatePayloadMappingFor: aNeoJSONMapper;
		guildMemberAddayloadMappingFor: aNeoJSONMapper;
		voiceStateUpdatePayloadMappingFor: aNeoJSONMapper;
		channelCreatePayloadMappingFor: aNeoJSONMapper;
		channelDeletePayloadMappingFor: aNeoJSONMapper;
		channelUpdatePayloadMappingFor: aNeoJSONMapper;
		unclassifiedPayloadMappingFor: aNeoJSONMapper.