accessing
dispatchMessageCreatePayloadString
	^ '{"t":"MESSAGE_CREATE","s":5,"op":0,"d":{"type":0,"tts":false,"timestamp":"2017-06-12T09:34:25.425000+00:00","pinned":false,"nonce":null,"mentions":[],"mention_roles":[],"mention_everyone":false,"id":"70273","embeds":[],"edited_timestamp":null,"content":"Message sent from the test case DSClientWithResourceTest>>#testSendTo at 2017-06-12T09:34:24.550686+00:00","channel_id":"309303547344715776","author":{"username":"user one","id":"56332","discriminator":"4510","avatar":null},"attachments":[]}}
'